export default Object.freeze({
  CREATE_USER: '/api/auth/register',
  GENERATE_TOKEN_FOR_NUMBER: '/api/auth/generate-token',
  VALIDATE_TOKEN: `/api/auth/validate-token`,
  LOGIN: `/api/auth/login`,
  FORGOT_PASSWORD: `/api/auth/forgot-password`,
  UPDATE_PASSWORD: `/users/password-update`,
  VALIDATE_RESET_PASSWORD_TOKEN: `/api/auth/validate-forgot-password-token`,
  RESET_PASSWORD: `/api/auth/process-password-reset`,
  CREATE_PIN: `/auth/create-pin`,
  UPDATE_PIN: `/auth/update-pin`,
  FORGOT_PIN: `/auth/forgot-pin`,
  VALIDATE_RESET_PIN_TOKEN: `/auth/validate-forgot-pin-token`,
  PROCESS_PIN_RESET: `/auth/process-pin-reset`,

  CONVERSATIONS: id => `/conversations/${id}`,
  CONVERSATION_INVITATION: id => `/conversations/${id}/invitations`,
  CONVERSATION_PARTICIPANTS: id => `/conversations/${id}/conversers`,
  CONVERSATION_MESSAGES: (id, messageId) => `/conversations/${id}/messages/${messageId}`,
  CREATE_EXPENSE_CONVERSATION: `/conversations/expense`,
  CONVERSATION_PRIVACY: id => `/conversations/${id}/privacy`,
  CONVERSATION_BILLS: id => `/conversations/${id}/bills`,
  ARCHIVE_CONVERSATION: id => `/conversations/${id}/archive`,
  DELETE_ARCHIVED_CONVERSATION: id => `/conversations/${id}`,
  ARCHIVED_CONVERSATIONS: `/conversations/archives/all`,
  GENERATE_CONVERSATION_SHARES: id => `/conversations/${id}/shares`,
  SHARED_CONVERSATION: reference => `/conversation-shares/${reference}`,
  RESPOND_TO_CONVERSATION_INVITATION: invitationId => `/conversation-invitations/${invitationId}`,
  LEAVE_CONVERSATION: id => `/conversations/${id}/exit`,
  REASSIGN_ADMIN: id => `/conversations/${id}/ownership`,
  REMOVE_PARTICIPANT: (id, converserId) => `/conversations/${id}/conversers/${converserId}`,
  UPDATE_CONVERSATION_READ_RECEIPT: id => `/conversations/${id}/message-acknowledgement-status`,
  SEND_CREATOR_MESSAGE: `/messagings`,

  EXPERIENCE: id => `/experiences/${id}`,
  EXPERIENCE_MEDIA: (id, mediaId) => `/experiences/${id}/medias/${mediaId}`,
  EXPERIENCE_SCHEDULES: id => `/experience-schedules/${id}`,
  EXPERIENCE_REPORT_TYPES: `/experience-report-types`,
  REPORT_AN_EXPERIENCE: id => `/tickets/${id}/experience-reports`,
  PERKS: `/perks`,

  BILLS: id => `/bills/${id}`,
  BILL_PAYMENT: reference => `/bill-quotas/${reference}/pay`,
  DECLINE_BILL_PAYMENT: reference => `/bill-quotas/${reference}/decline`,
  BILL_REMINDER: reference => `/bill-quotas/${reference}/reminder`,
  GET_BILL_QUOTA_DETAILS: reference => `/bill-quotas/${reference}`,
  GET_EXTERNAL_BILL_QUOTA_DETAILS: reference => `/bill-quotas/${reference}/external`,

  CREATE_BOOKING: `/bookings`,
  BOOKINGS: id => `/bookings/${id}`,
  CANCEL_BOOKING: id => `/bookings/${id}/cancel`,
  GET_BOOKING_CANCELLATION_DETAILS: id => `/bookings/${id}/cancellation-details`,

  REQUEST_BANK_LIST: '/banks',
  RESOLVE_ACCOUNT_DETAILS: '/bank-details/resolve',
  ACCOUNT_DETAILS: id => `/bank-details/${id}`,

  BUSINESS: id => `/businesses/${id}`,
  GET_COUNTRIES: `/countries`,
  GENDER: `/genders`,
  SERVICES: id => `/services/${id}`,
  LANGUAGES: id => `/languages/${id}`,
  INITIATE_UPLOAD: `/uploads/initiate`,
  GET_EXPERIA_USERS: `/users/phonenumbers/search`,
  VERIFY_PROFILE: `/kyc/verify`,

  PROFILE: `/profile/me`,
  UPDATE_PROFILE: `/profile`,
  GET_USER_WALLET: `/profile/wallet`,
  GET_USER_BOOKINGS: `/profile/bookings`,
  GET_USER_TICKETS: id => `/profile/tickets/${id}`,
  GET_USER_CONVERSATION_INVITATIONS: `/profile/conversation-invitations`,
  GET_USER_TRANSACTIONS: `/profile/transactions`,
  GET_USER_ACTIVITIES: `/profile/activities`,
  GET_USER_CURRENCY_INFO: `/users/ip/currency`,

  REFILL_WALLET: `/wallets/refill`,
  WITHDRAW: `/wallets/withdraw`,

  VERIFY_PAYMENT: reference => `/payments/${reference}/verification/paystack`,
  TRANSACTIONS: id => `/transactions/${id}`,

  UPDATE_ACTIVITIES_READ_RECEIPT: `/activities/status`,
  PROVISIONS: id => `/provisions/${id}`
});
